"""Download public-domain Bach BGM and synthesize Russian male VO (not music)."""
from __future__ import annotations

import asyncio
import json
import re
import subprocess
from pathlib import Path

PROJ = Path(__file__).resolve().parents[1]
ROOT = PROJ.parent
VOICE_DIR = PROJ / "assets" / "voice"
BGM_DIR = PROJ / "assets" / "bgm"
FFMPEG_BIN = Path(
    r"C:\Users\user\AppData\Local\Microsoft\WinGet\Packages"
    r"\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe\ffmpeg-9.0-full_build\bin"
)
FFMPEG = str(FFMPEG_BIN / "ffmpeg.exe")
FFPROBE = str(FFMPEG_BIN / "ffprobe.exe")
BACH_URL = "https://upload.wikimedia.org/wikipedia/commons/1/1e/Air_(Bach).ogg"
LINES = [
    (1, "ДИС Аналитик 360 — персональный AI-помощник для анализа данных."),
    (2, "Загрузите таблицу, документ или изображение."),
    (3, "Система проверит качество данных, найдёт пропуски и дубликаты и рассчитает основные показатели."),
    (4, "Задавайте вопросы обычными словами и получайте понятные выводы."),
    (5, "ДИС строит интерактивные графики непосредственно по исходным данным."),
    (6, "Ход обработки отображается в реальном времени, а результаты можно сохранить."),
    (7, "ДИС Аналитик 360. Загрузил, спросил, понял."),
]
SCENE_WINDOWS = {1: 5.0, 2: 8.0, 3: 10.0, 4: 10.0, 5: 10.0, 6: 8.0, 7: 9.0}


def duration_of(path: Path) -> float:
    probe = subprocess.run(
        [FFPROBE, "-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", str(path)],
        capture_output=True,
        text=True,
        check=True,
    )
    return float(probe.stdout.strip())


def split_words(text: str, total: float) -> list[dict]:
    tokens = [t for t in re.findall(r"\S+", text) if t]
    if not tokens:
        return []
    weights = [max(len(re.sub(r"\W+", "", t, flags=re.U)), 1) for t in tokens]
    scale = total / sum(weights)
    words = []
    t = 0.08
    for i, (tok, w) in enumerate(zip(tokens, weights)):
        dur = max(0.12, w * scale * 0.92)
        words.append({"id": f"w{i}", "text": tok, "start": round(t, 3), "end": round(t + dur, 3)})
        t += dur + 0.04
    if words:
        words[-1]["end"] = round(min(total - 0.05, max(words[-1]["end"], t - 0.04)), 3)
    return words


async def tts_line(edge_tts, frame: int, text: str) -> Path | None:
    VOICE_DIR.mkdir(parents=True, exist_ok=True)
    dest = VOICE_DIR / f"{frame:02d}.mp3"
    communicate = edge_tts.Communicate(text, "ru-RU-DmitryNeural")
    await communicate.save(str(dest))
    wav = VOICE_DIR / f"{frame:02d}.wav"
    subprocess.run(
        [FFMPEG, "-y", "-i", str(dest), "-ac", "1", "-ar", "44100", str(wav)],
        check=True,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    return wav


def ingest_bach() -> Path:
    BGM_DIR.mkdir(parents=True, exist_ok=True)
    ogg = BGM_DIR / "air-bach.ogg"
    if not ogg.exists() or ogg.stat().st_size < 1000:
        subprocess.run(
            ["curl", "-L", "--fail", "--user-agent", "DIS-Analyst-360-promo/1.0 (educational)", "-o", str(ogg), BACH_URL],
            check=True,
        )
    mp3 = BGM_DIR / "track.mp3"
    # Calm mid-section of the 1920 recording, 60s bed with fades. Not synthesized.
    subprocess.run(
        [
            FFMPEG, "-y", "-ss", "12", "-i", str(ogg), "-t", "62",
            "-af", "afade=t=in:st=0:d=1.2,afade=t=out:st=60.5:d=1.5,loudnorm=I=-22:TP=-2:LRA=11",
            "-ar", "44100", "-ac", "2", str(mp3),
        ],
        check=True,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    (BGM_DIR / "SOURCE.txt").write_text(
        "Johann Sebastian Bach — Air on the G String (BWV 1068), 1920 recording\n"
        "Violin: Joel Belov; piano: Robert Gayler.\n"
        "Source: Wikimedia Commons File:Air_(Bach).ogg — public domain.\n"
        f"URL: {BACH_URL}\n"
        "This file was ingested, not generated by an AI music model.\n",
        encoding="utf-8",
    )
    return mp3


async def main() -> None:
    ingest_bach()
    voices = []
    try:
        import edge_tts
    except ImportError:
        subprocess.run([sys_executable(), "-m", "pip", "install", "-q", "edge-tts"], check=True)
        import edge_tts  # type: ignore

    for frame, text in LINES:
        try:
            wav = await tts_line(edge_tts, frame, text)
        except Exception as exc:
            print("TTS failed for frame", frame, exc)
            wav = None
        if not wav or not wav.exists():
            continue
        dur = duration_of(wav)
        voices.append(
            {
                "frame": frame,
                "path": f"assets/voice/{frame:02d}.wav",
                "duration_s": round(dur, 3),
                "words": split_words(text, dur),
            }
        )
        print("voice", frame, dur)

    meta = {
        "bgm": {
            "path": "assets/bgm/track.mp3",
            "volume": 0.12 if voices else 0.35,
            "query": "public-domain Bach Air on the G String 1920 recording",
            "duration_s": round(duration_of(BGM_DIR / "track.mp3"), 3),
            "mode": "ingest",
        },
        "bgm_pending": False,
        "voices": voices,
        "sfx": [],
    }
    (PROJ / "audio_meta.json").write_text(json.dumps(meta, ensure_ascii=False, indent=2), encoding="utf-8")
    print("wrote audio_meta.json", len(voices), "voices")


def sys_executable() -> str:
    import sys
    return sys.executable


if __name__ == "__main__":
    asyncio.run(main())
